apiVersion: v1
kind: Service
metadata:
  name: {{ include "lehigh-liftoff.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: api-server
    {{- include "lehigh-liftoff.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: api-server
    {{- include "lehigh-liftoff.selectorLabels" . | nindent 4 }}
