{{- define "authJWTData" -}}
{{- $chartFullName := include "lehigh-liftoff.fullname" . -}}
{{- $secretName := printf "%s-auth" $chartFullName -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{- if $secret }}
{{- $secret.data.jwt_secret -}}
{{- else -}}
{{- randAlphaNum 1024 | b64enc -}}
{{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lehigh-liftoff.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: api-server
    {{- include "lehigh-liftoff.labels" . | nindent 4 }}
type: Opaque
data:
  oauth_client_id: {{ printf "%s" .Values.oauth.clientId | b64enc }}
  oauth_client_secret: {{ printf "%s" .Values.oauth.clientSecret | b64enc }}
  oauth_service_domain: {{ printf "%s" .Values.oauth.serviceDomain | b64enc }}
  jwt_secret: {{ template "authJWTData" . }}
  elastic_host: {{ printf "%s" .Values.elastic.host | b64enc }}

