apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lehigh-liftoff.fullname" . }}-pg
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: api-server
    {{- include "lehigh-liftoff.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ printf "%s" .Values.postgres.user | b64enc }}
  password: {{ printf "%s" .Values.postgres.password | b64enc }}
  host: {{ printf "%s" .Values.postgres.host | b64enc }}
  port: {{ printf "%s" .Values.postgres.port | b64enc }}
  database: {{ printf "%s" .Values.postgres.database | b64enc }}

