{{- if .Values.image.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lehigh-liftoff.fullname" . }}-pull-creds
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "lehigh-liftoff.imagePullSecret" . }}
{{- end }}

